# pushState friendly!
# The setup:
#   * javascript app is located at `${APP_WORKDIR}`

charset utf-8;

gzip on;
tcp_nopush on;
tcp_nodelay off;
client_header_timeout ${CLIENT_HEADER_TIMEOUT}s;
client_body_timeout ${CLIENT_BODY_TIMEOUT}s;
client_max_body_size ${CLIENT_MAX_BODY_SIZE}k;
server_tokens off;
reset_timedout_connection on;

gzip_types
    text/css
    text/javascript
    text/xml
    text/plain
    application/javascript
    application/x-javascript
    application/json
    application/xml
    application/rss+xml
    application/atom+xml
    font/truetype
    font/opentype
    image/svg+xml
    image/png;

map $sent_http_content_type $expires {
  default                    off;
  text/html                  epoch;
  /static/                   30d;
}

server {
  listen 80;
  root ${APP_WORKDIR};

  error_page 404 @rewrites;

  # To make sure any assets can get through :)
  location / {
    try_files $uri $uri/ @rewrites;

    # BEGIN_CONFIG_WHEN_WHITE_LIST_ON
		if ($proxy_add_x_forwarded_for !~ "^${WHITE_LIST_IP}$") {
			return 403;
		}
    # END_CONFIG_WHEN_WHITE_LIST_ON
  }

  # # PREFIX PATH
  # location ${APP_BASENAME}/ {
  #   rewrite ^${APP_BASENAME}/(.*) /$1  last;
  # }

  # BEGIN_CONFIG_WHEN_APP_BASENAME_ON
  location ^~ ${APP_BASENAME} {
    alias ${APP_WORKDIR};
    try_files $uri $uri/ @rewrites;
  }
  # BEGIN_CONFIG_WHEN_APP_BASENAME_OFF


  location ~ ^/health {
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
    add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';

    if ($request_method = 'OPTIONS') {
        return 204;
    }

    default_type application/json;
    return 200 '{"version":"${APP_VERSION}","status":"OK","build":"${BUILD}","debug":"${DEBUG}"}';
  }

  # If no asset matches, send it to your javascript app. Hopefully it's a route in the app!
  location @rewrites {
    rewrite ^(.+)$ /index.html last;
  }

  expires $expires;

}